[package]
name = "gb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "*"
sdl2 = "0.35"
tui = "*"
crossterm = "*"
md5 = "*"
